In [1]:
import numpy as np
arr =  np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
#indexing arrays
arr[4]


4

In [4]:
arr[2:6]

array([2, 3, 4, 5])

In [5]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[0:-4]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
#broadcast values 
arr[0:6] = 20 

In [10]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10, 11])

In [11]:
#in python numpy array the data is not copied its just the view of the original data 
# shown in a chunk
Array1=np.arange(0,16)
sliceOfArray= Array1[0:9]
#slice of array
sliceOfArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
#making changes to the slice of the array
sliceOfArray[0:4]=100
sliceOfArray

array([100, 100, 100, 100,   4,   5,   6,   7,   8])

In [13]:
#printing the main array
Array1
#here also the value is changed 

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [14]:
#copyiing an array 
newArray = Array1.copy()
newArray

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [15]:
#if we make changes to this array and then printing the original array then the values will not change at all
newArray[0:7]=100
newArray

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [16]:
Array1

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [19]:
array2=np.random.randint(0,19,9).reshape(3,3)
array2

array([[ 7,  4,  3],
       [ 2, 13,  0],
       [11,  0,  9]])

In [20]:
#indexing a 2d Array element
array2[2][2]

9

In [21]:
#another type of notation
array2[1,2]

0

In [24]:
#slicing the matrix
array2[:2,0:2]

array([[ 7,  4],
       [ 2, 13]])

In [25]:
#operators in numpy
array2 > 4

array([[ True, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [27]:
boolArray= array2 >4

In [28]:
array2[boolArray]

array([ 7, 13, 11,  9])