In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1 = arr+arr
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr2=arr1*arr1
arr2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [7]:
arr3=arr2-arr1
arr3

array([  0,   2,  12,  30,  56,  90, 132, 182, 240, 306, 380])

In [10]:
arr4 = arr3[0:5]
arr4+101

array([101, 103, 113, 131, 157])

In [11]:
arr3

array([  0,   2,  12,  30,  56,  90, 132, 182, 240, 306, 380])

In [12]:
arr3+10

array([ 10,  12,  22,  40,  66, 100, 142, 192, 250, 316, 390])

In [13]:
arr3/arr1

C:\Users\Lucifer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [14]:
1/arr1

C:\Users\Lucifer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       , 0.08333333, 0.07142857, 0.0625    , 0.05555556,
       0.05      ])

In [15]:
arr4 ** 3

array([     0,      8,   1728,  27000, 175616], dtype=int32)

In [16]:
np.sqrt(arr4)

array([0.        , 1.41421356, 3.46410162, 5.47722558, 7.48331477])

In [18]:
arr3.max()

380

In [19]:
#provide sine angle values 
np.sin(arr3)

array([ 0.        ,  0.90929743, -0.53657292, -0.98803162, -0.521551  ,
        0.89399666,  0.05308359, -0.21078107,  0.94544515, -0.95376171,
        0.13232187])

In [20]:
#provides log value for values in the array 
np.log(arr3)

C:\Users\Lucifer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.69314718, 2.48490665, 3.40119738, 4.02535169,
       4.49980967, 4.88280192, 5.20400669, 5.48063892, 5.7235851 ,
       5.94017125])