In [1]:
import numpy as np
#creating a list 
my_list = [1,5,4,7,8,4,59,5,2,3]
#casting list to array
new_List=np.array(my_list)

In [2]:
new_List

array([ 1,  5,  4,  7,  8,  4, 59,  5,  2,  3])

In [4]:
#creating a 2D array
myList2D = [[2,1,4],
           [4,5,8],
           [9,6,3]]
#casting into a matrix 
np.array(myList2D)

array([[2, 1, 4],
       [4, 5, 8],
       [9, 6, 3]])

In [8]:
#creating 1D array using arrange funtion 
#arange function iterate number present in a particular range e.g:
#resultiing in a array of the range 
Array1=np.arange(0,18)
Array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [9]:
#arange function having a step function as well
# np.arange(0,11,2) results in a series of numbers from 0 to 10 with step function 2
Array2=np.arange(0,19,2)
Array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#creating an array of all zeroes we'll have zeros function with the body size
Array3=np.zeros((3,5))
#result in a array of size 3x5
Array3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#creating an array of all ones we'll have zeros function with the body size
Array4 = np.ones((4,6))
Array4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
#linspace results in evenly spaced sequence of numbers between a given range 
Array4=np.linspace(0,5,9)
Array4

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [17]:
#creating a identity matrix of order n
Array5=np.eye(5)
Array5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
#takes random values between 0-1 by default
#argument passed will be the size of the matrix
np.random.rand(5)

array([0.59612981, 0.65593057, 0.48485516, 0.97387205, 0.93364126])

In [20]:
np.random.rand(2,4)

array([[0.4735248 , 0.66377086, 0.26701817, 0.40615336],
       [0.43839892, 0.19549569, 0.47893817, 0.25668857]])

In [23]:
# if  we need a random intergerr in a particular range then we'll use a particular function
np.random.randint(1,100,4)
#result in 4 random numbers between 1-100

array([43, 28, 18, 71])

In [30]:
#for shaping up a particular datase we'll use reshape function 
#arguments we'll have is the size of the matrix
Array6=np.random.randint(0,100,12).reshape(3,4)
Array6

array([[76, 71, 28, 90],
       [36,  9, 63, 14],
       [ 2, 13, 30, 93]])

In [31]:
#return the maximum value in the array
Array6.max()


93

In [33]:
#return the minimum value in the array
Array6.min()

2

In [35]:
#if we need the index of  max and min value we'll use the argmax/argmin
Array6.argmax()

11

In [36]:
Array6.argmin()

8

In [38]:
#checking the shape of the matrix or an array
Array6.shape

(3, 4)

In [40]:
#checking the datatype 
Array6.dtype

dtype('int32')